# Generated by Django 2.0 on 2017-12-07 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
